# Author: LucasPacheco

################################
EXE = hellosine#
################################

# Folders Flags


# Command Flags
CC      = gcc
OBJFLAG = -c
EXEFLAG = -o
HS_FLAG = -I
MTHFLAG = -lm

all:
	$(CC) $(OBJFLAG) $(EXE).c 
	$(CC) $(EXEFLAG) $(EXE) $(EXE).o $(MTHFLAG)

run:


clean:
	rm ./*.o
	clear

cleanAll:
	rm ./*.o
	rm ex
	clear
